### ISSUE TITLE
Speed Module 3 wrong recipe

### ISSUE THREAD

**Issue by Sadumon** [doomeer/factorio#13]
Speed Module 3 is incorrectly set to use only 4 of the speed module 2, but it requires 5 like the other modules.

Line 325-7 of recipes.ml:
let speed_module_3 =
  res "Speed Module 3" am2 60.
[ 5., advanced_circuit; 5., processing_unit; **4., speed_module_2 ]**

**Comment by doomeer** [comment]
Fixed, thanks a lot for the patch, it makes it much easier for me ;)
