### ISSUE TITLE
Rocket silo missing speed and productivity support

### ISSUE THREAD

**Issue by Grokzen** [doomeer/factorio#19]
Can't calculate the requirements for `Rocket part` because speed and productivity can't be set for rocket silo.

**Comment by doomeer** [comment]
That's weird, I added this a couple weeks ago (here is an example: http://www.doomeer.com/factorio/index.html#1132bbbbbbbbbbbb100rgrgrrrrgrrrgrgrrrrrrrrrrrrrrrrrrrrrrrrgrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr1rr). Am I missing something? Or are you by chance using another website? The tool is hosted at other places, maybe their maintainers did not pull the changes yet.

**Comment by Grokzen** [comment]
I used this one https://dwahler.github.io/factorio/index.html

Your have the update. Closing this ticket.
