### ISSUE TITLE
Show shared-production-building-usage on each line-item

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [doomeer/factorio#20]
Let's say I'm producing a bunch of stone stuff:

<img width="541" alt="screen shot 2017-06-13 at 13 56 28" src="https://user-images.githubusercontent.com/200/27099305-1fa788a0-5040-11e7-8393-b8873aa12b25.png">

So when I set, say, “stone block” as a ‘shared item’ (because on the production-line I'm planning, I'm throwing it on a belt, and it's going to be used in multiple recipes, and I want to know the *total* number of stone-block assemblers — well, furnaces, in this case — I need to feed the N recipes along that line that are consuming it), I can see the total up at the top:

<img width="309" alt="screen shot 2017-06-13 at 13 56 54" src="https://user-images.githubusercontent.com/200/27099323-2e0b8f2c-5040-11e7-8402-f421cb8cd537.png">

… which is, of course, kinda the point.

But when I look at that, and wonder, “woah, why the frack do I need *seven* furnaces!?”, I look back down below, and unfortunately,

<img width="332" alt="screen shot 2017-06-13 at 13 58 00" src="https://user-images.githubusercontent.com/200/27099375-562c491a-5040-11e7-99e5-efa60a2b261f.png">

… the individual line-items are no longer showing how much assembler- (and thus space-) usage they're contributing to the overall production-line.

When designing a complex line, this becomes a lot of math to do in my head — I'd love to see the usage, per-line-item, re-added. Even better, since with a “shared resource” we know the *total* number of assemblers, it'd be ideal if each line-item actually showed the total, and the percentage thereof, for shared resources:

<img width="441" alt="screen shot 2017-06-13 at 14 04 35" src="https://user-images.githubusercontent.com/200/27099665-43530b02-5041-11e7-90a1-57540d9defc3.png">

(Forgive the horrible HTML-edit mockup, but I hope you get the idea!)

**Comment by doomeer** [comment]
Interesting; it looks rather simple to implement, not invasive (maybe I'd just put the percentage though, in gray) and useful. I'll try to add it next time I open up Emacs :D

**Comment by doomeer** [comment]
Done!

**Comment by ELLIOTTCABLE** [comment]
Beautiful! <3
