### ISSUE TITLE
Fix name of Pump

### ISSUE THREAD

**Issue by CPonty** [doomeer/factorio#22]
The image for pumps has been renamed in the wiki as of v0.15

In **factoriojs.ml**: `pump.name, "Small-pump";` -> `pump.name, "Pump";`

https://wiki.factorio.com/images/Pump.png
https://wiki.factorio.com/Images/Small-Pump.png

**Comment by CPonty** [comment]
(yes this is a trivial change, but I'm at work on break, so I'm not installing ocaml to recompile the JS)

**Comment by doomeer** [comment]
Thanks for the notice! I'll make sure this is fixed soon :) Don't worry about triviality ;)

**Comment by doomeer** [comment]
Fixed :)
