### ISSUE TITLE
Explanation for blue percentage next to resources

### ISSUE THREAD

**Issue by dassmann** [doomeer/factorio#23]
Hi!

What does the blue percentage next to the 'resource / sec' indicate?

See here:
![screenshot from 2017-06-26 10-07-55](https://user-images.githubusercontent.com/604574/27530147-a79c1a0c-5a57-11e7-9c3f-69067d19bd38.png)

Thanks!

**Comment by doomeer** [comment]
See this: https://github.com/doomeer/factorio/issues/20

It shows how much of the total for this resource this particular instance represents.

Thanks for asking, this shows that it could use more explanation in the tool! I'll try to add it to the entry page.

**Comment by dassmann** [comment]
Thanks!
