### ISSUE TITLE
Full Speed Machines & minutes 

### ISSUE THREAD

**Issue by edipp** [doomeer/factorio#34]
Hi,
Using the setting A1 B1 or C1, with the time unit minutes leads to a miscalculation.
1 A Assembler makes 0,25 Red Science per second
should be: 0,25*60sec/min=15 Red Science per minute
instead the Planners output is: 0.25/min (Assembling Machine 2 × 0.028 or Assembling Machine 3 × 0.017)

Example:

http://doomeer.com/factorio/index.html#s1132bbbbbbbbbbbbbbrgrgrrrrgrrrgrgrrrrrrrrrrrrrrrA1rrrrrrrrrgrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

http://doomeer.com/factorio/index.html#m1132bbbbbbbbbbbbbbrgrgrrrrgrrrgrgrrrrrrrrrrrrrrrA1rrrrrrrrrgrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by doomeer** [comment]
Indeed! Thanks for the notice, I'll get this fixed.

**Comment by doomeer** [comment]
Done!
