### ISSUE TITLE
Documentation: Tips section should make it clearer regarding "fastest machines"

### ISSUE THREAD

**Issue by stwalkerster** [doomeer/factorio#36]
Currently, the Tips section states:

> Instead of entering the requested throughput, you can enter a number of machines that should run at full speed. To this end, simply prefix the number by the letter A to use the fastest machine, B to use the second best or C to use the third best. For instance, requesting b2 laser turrets means that 2 blue assembling machines should run at full speed.

If I wish to only use blue machines, I enter "B2" into the box as the second sentence directed me to, and then disabled the yellow machines in the advanced settings. This makes the calculation vanish (see #35)

Instead, what actually appears to happen is that the yellow machines are no longer the "fastest", and so blue machines should be entered with "A1" not "B1" into the box. It is also worthy of note that the grey machines are not enabled by default, so entering "C1" into the box as suggested in the documentation will not work unless the machine is enabled in advanced settings.

It would be nice to see this made more clear in the documentation - I think a behavioural change would likely break existing saved plans that others have bookmarked?

**Comment by doomeer** [comment]
Changing the behavior would indeed break existing plans, but on the other hand, there has already been several patches which broke existing plans. I think it would however be confusing for users which are used to the current behavior.

That being said I agree that the documentation could be more clear, I'll try to improve it.

**Comment by doomeer** [comment]
I improved the documentation, it's longer but I hope it's easier to understand.
