### ISSUE TITLE
Display belt throughput for resources

### ISSUE THREAD

**Issue by stwalkerster** [doomeer/factorio#38]
Assuming I have [the following plan](http://doomeer.com/factorio/#s1122bbbbbbbbbbbbbbrgrgrrrrgrrrgrgrgrgrrgrrrrrgrgrrrrrrrrrr1rrrrgrrrgrgrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr) designed:

![image](https://user-images.githubusercontent.com/722710/28985903-a42f7f7a-795c-11e7-8307-3c9ea552c75a.png)

I can tell at-a-glance that a single compressed belt of copper plate is likely insufficent to supply these factories, a feeling that is [backed up by the data](https://wiki.factorio.com/Transport_belts/Physics#Theory). From a quick calculation, I would need about 2.45 fully-compressed red belts to supply the necessary copper for this.

It would be nice to see something like this to see what kind of supply would also be needed:

![image](https://user-images.githubusercontent.com/722710/28986173-c213ae5c-795d-11e7-8103-c328b60205df.png)

**Comment by breathermachine** [comment]
Should be merged with this issue: https://github.com/doomeer/factorio/issues/28

**Comment by stwalkerster** [comment]
Indeed it should, my apologies for not spotting that one earlier!
