### ISSUE TITLE
Iron to Steel calculation error?

### ISSUE THREAD

**Issue by firefly762** [doomeer/factorio#40]
I'm not sure if my math is wrong (my brain is pretty fried at the moment, so everything with a grain of salt :P); in every recipe that requires steel plate, it shows too much iron plate required to produce that much steel plate. (e.g. 5 SP/s requires 25 IP/s which should, I think, require only 10 iron per second). I believe your formula may have (# of steel plates)^2 = # of iron plates when it should be (# of steel plates)*2 = iron plates...if I'm wrong, please explain why it is squared not doubled because my brain is not comprehending this (could be that it is an ungodly hour, but I'm still curious).

Cheers

EDIT
It seems the error is in the number of steel plates produced by the correct number of furnaces. It shows equal numbers of furnaces (which is correct) between iron and steel, but the steel is the perfect square root of the iron output every time....math time: Electric Furnace has a craft speed of 2, Steel has a craft time of 7 seconds. 2/7*43.75 = 12.5...
![factorio explanation](https://user-images.githubusercontent.com/32155412/30682886-84acc7a8-9e68-11e7-9737-d61d52a94c1d.jpg)

**Comment by breathermachine** [comment]
Steel throughput = Iron throughput / 5. It just happened that you used 5 SP/s and it gave you 25 IP/s leading you to the impression that SP = sqrt(IP). Try inputting 40 SP/s. It will give you 200 IP/s which is definitely not 40*40.

**Comment by firefly762** [comment]
Aaaahhh, you are correct it is only multiplied by 5 not squared, though it is still incorrect; it only takes twice as much iron than steel. It's a minor detail, but it can throw a big wrench into the calculations for a large factory.

**Comment by breathermachine** [comment]
No. Unless you are using productivity modules, the ratio would still be 5:1. Where did you get the "it only takes twice as much iron as steel" idea?

**Comment by firefly762** [comment]
Because I'm an idiot and just now realized I have a mod that changes the amount of iron plates to make a steel plate.... :P This is why you shouldn't be trying to do mathmagician stuff at 3am...thanks.
