### ISSUE TITLE
Organize list of items

### ISSUE THREAD

**Issue by JuicyJuuce** [doomeer/factorio#51]
@doomeer I think splitting up the items into the groups that they appear in the in-game crafting menu (Logistics, Production, Intermediate products, Combat) would be a good way to break it up and organize them. Actually, in order to include items not in the crafting menu like liquids and raw materials, the "signal" menu should be used as the reference (the menu that pops up whenever you select an input or output box in a combinator).

**Comment by doomeer** [comment]
That's a very good idea!

**Comment by hagfish** [comment]
This tool is excellent - I use it all the time. I have one feature request, however: the ability to adjust the game 'difficulty' settings. This would be particularly helpful for determining the amount of _raw_ resources required to support a particular output on a marathon or death-world. 

Most recipes stay the same, but those that are affected, are affected a _lot_.

**Comment by Saintis** [comment]
I like the new categories. I found the "Rocket" category especially useful.

I'd find a separate "Science" category useful as well, as that's how I mainly use the planner.

**Comment by doomeer** [comment]
Thanks for your patch @Saintis!
