### ISSUE TITLE
Unable to use Battery as shared resource

### ISSUE THREAD

**Issue by IceReaper** [doomeer/factorio#53]
http://doomeer.com/factorio/index.html#s1112bbbbbbbbbbbbbbrrgrrrrrrrrgrgrgrgrrgrrrgrrgrgrgrrrr3r3r3r3r3r3r3rrrrrrrgrgrrrrrrrrrrrrrrrrrrrrrrgrrrrrrrrrrrrrrrrrrrrrrrgrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

Battery checkbox is set but gets ignored.

**Comment by ecazbar** [comment]
It appears that what you have checked is actually "battery equipment", and they just have the wrong icon for it. Look for the battery component near plastic bar and iron stick higher in the list.

Devs - You should probably correct the icon on battery equipment mk1.

I appreciate the awesome planning tool.

**Comment by DeCristoforis** [comment]
Fixed in pull request #55

**Comment by doomeer** [comment]
Thanks for the report and thanks again for the fix!
