### ISSUE TITLE
Updates to expensive recipes for 0.15

### ISSUE THREAD

**Issue by werelord** [doomeer/factorio#6]
Not really an issue.. but with 0.15 out, are there any plans on updating the recipe ratios when expensive recipe difficulty are selected with map generation?? For example, with expensive recipes green circuits require 10 copper wire and 2 iron (making a 5/1 ratio copper wire/green circuit)..

Would love to keep using this with 0.15 expensive recipes..

**Comment by mdavidn** [comment]
Just came here looking for this myself. Wanted to see what me and my friends were getting into with our new marathon game.

**Comment by werelord** [comment]
There's a fork that teraflop posted on the reddit that contains the 0.15 new normal recipes. reddit thread: https://www.reddit.com/r/factorio/comments/67ma95/i_updated_doomeers_webbased_planning_tool_for_015/

as I commented on that thread, the expensive recipes could be done by modifying the recipes.ml file, but I haven't had the time to do so..

**Comment by s3bash** [comment]
Quick and dirty, a branch for expensive recipes can be done. Adding a switch for normal/expensive would be longer.

**Comment by doomeer** [comment]
I merged s3bash's pull request. If there are missing or wrong recipes, please tell me! Or better yet, make a pull request :D Thanks again!
