### ISSUE TITLE
.17 recipes

### ISSUE THREAD

**Issue by Lava84flow** [doomeer/factorio#64]
Not exactly an issue, yet, but pretty much just wondering if you were planning on getting things updated to the new recipes for .17 soon, or did you want someone else to start work on that?

**Comment by rbardou** [comment]
Well, I have not played Factorio for quite a while now, so it would be very helpful if someone else worked on the .17 recipes. If someone makes a pull request, I will try to have it merged as soon as possible. Thanks for the notice by the way, I was not aware the .17 was coming soon =)

**Comment by Lava84flow** [comment]
Yeah, looks like it's coming semi-early February. I'd do it if the thing was already in JS and not just complied to JS, not that I would not go learn OCaml, I just really don't have time right now. Darn you, everything but OCaml classes...

**Comment by rbardou** [comment]
Hehe :) Well, recipes are in the recipes.ml file. If you copy-paste existing recipes, you (or anybody willing to do it) would find it reather easy to add new ones, I believe. You also have to add the new variable in the recipe list at the end. If you do that, don't bother installing OCaml, just make the PR and I'll fix syntax errors and compile into JS.

**Comment by Lava84flow** [comment]
Probably should wait on that until they actually release at the experimental builds. Right now, while all the basic parts of the new recipes have been laid out in the FFF's, the exact specifics and anyone but Wube's guess.

**Comment by Lava84flow** [comment]
let me know if I royally screwed everything or not
