### ISSUE TITLE
Wrong mining productivity

### ISSUE THREAD

**Issue by DeCristoforis** [doomeer/factorio#8]
For example, iron/copper/coal ores productivity mined by electric drill is 0.525/s, but planner uses value 0.5/s. For stone - 0.65/s but planner uses still 0.5/s. There is small workaround - using 5% productivity bonus makes ore mining speed equal to 0.525/s, but for stone...
Formula uses (Mining_power - Mining_hardness) factor, that depends on ore-drill pair, so it's not so simple to make this change.

**Comment by doomeer** [comment]
Thanks for the notice and for the patch! I like how you implemented it :)
