### ISSUE TITLE
Example site (doomeer.com) is down

### ISSUE THREAD

**Issue by tylerault** [doomeer/factorio#80]
The example site at:
http://doomeer.com/factorio

...is currently down:
**This site can’t be reached**
doomeer.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

I flushed DNS cache & still can't reach. Request originated from northeastern USA.

**Comment by C7C8** [comment]
I've temporarily re-hosted the site [here](https://crmyers.dev/factorio), on my own personal website (which is otherwise entirely empty). Hope it helps!

**Comment by devosray** [comment]
Since I am used to just typing "doomeer" into the URL bar and having it auto-fill, I have _also_ rehosted at https://doomeer.wonnieraad.co.za to make my life ever-so-slightly easier 😄

**Comment by doomeer** [comment]
Sorry about that, I forgot to renew my domain. This is all fixed now :D Thank you for rehosting!
